package bn.nook.alchemy.utils;

/**
 * Created by avsupport on 3/5/14.
 */
public enum ConfigurationParametersEnum {
    MOBILE_PLATFORM,

    ANDROID_APP_DIR,
    ANDROID_APP,
    ANDROID_PLATFORM_VERSION,
    ANDROID_APP_PACKAGE,
    ANDROID_APP_ACTIVITY,
    ANDROID_DEVICE_ID,
    ANDROID_PLATFORM_NAME,

    IOS_APP_DIR,
    IOS_APP,
    IOS_PLATFORM_VERSION,
    IOS_PLATFORM_NAME,
    IOS_APP_PACKAGE,
    IOS_DEVICE_ID,
    IOS_DEVICE,

    LOGIN,
    PASSWORD,
    NET,
    BUILD,
    TIMEOUT,
    SYNC_COMPLETE,

    DATE_FIELD_NAME,
    TIME_FIELD_NAME,
    BUILD_FIELD_NAME,
    HW_FIELD_NAME,
    OS_FIELD_NAME,
    NET_FIELD_NAME,
    DEVICE_ID_FIELD_NAME,
    SLAVE_ID_FIELD_NAME,
    TEST_TYPE_FIELD_NAME,
    TEST_ID_FIELD_NAME,
    TEST_NAME_FIELD_NAME,
    TEST_ACTION_FIELD_NAME,
    TEST_DATA_FIELD_NAME,
    USED_MEMORY_FIELD_NAME,
    START_TIME_FIELD_NAME,
    END_TIME_FIELD_NAME,
    TOTAL_TIME_FIELD_NAME,
    TEST_RESULT_FIELD_NAME,
    TEST_CYCLE_FIELD_NAME,;

}
